* bconatr.js

Browser CONsole Assignment Test Runner, or BCONATR.

Pronounced "Baconator", written ~bconatr~ or ~bconatr.js~.

** Introduction

~bconatr.js~ is a very small library for use by code educators to allow them to write a specific kind of assignment, one that is:

1. unit-test-driven, to give learners fast feedback on whether their code meets requirements
2. runnable in a browser to avoid complex terminal setups for new coders

** Version

We are currently at version 0.1, so the API is still unstable. See the Usage section for where we're currently at.

** Usage

This section will be expanded once the API has settled down.

*** Basic Setup

**** Include This Library

Include the following tag in the ~<head>~ tag of your HTML file:

#+begin_src html
  <script src="https://cdn.jsdelivr.net/gh/abbreviatedman/bconatr-js/index.js"></script>
#+end_src

**** Write Tests

Write tests in a separate JavaScript file. Load that file /after/ ~bconatr.js~.

See the [[https://github.com/abbreviatedman/example-bconatr-js-assignment][example assignment]] to see an example of how to load it in, as well as what these tests could look like.
